import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { Card, Eyebrow, IconBadge, Pill, SectionTitle, Stat, palette, styles as ui, impact } from "@/components/rematter-ui";

const cities = [
  { name: "Ahmedabad", x: "23%", y: "38%", color: palette.mint, pods: 15, batches: 8, note: "Primary pilot hub" },
  { name: "Mumbai", x: "18%", y: "57%", color: palette.teal, pods: 11, batches: 6, note: "Collection active" },
  { name: "Delhi", x: "53%", y: "18%", color: palette.blue, pods: 18, batches: 12, note: "Processing partner" },
  { name: "Bengaluru", x: "43%", y: "79%", color: palette.amber, pods: 9, batches: 5, note: "Manufacturer cluster" },
  { name: "Hyderabad", x: "57%", y: "65%", color: palette.coral, pods: 7, batches: 4, note: "Expansion signal" },
  { name: "Pune", x: "29%", y: "62%", color: palette.mint, pods: 6, batches: 3, note: "Collection active" },
  { name: "Chennai", x: "62%", y: "86%", color: palette.blue, pods: 5, batches: 2, note: "Potential hub" },
  { name: "Kolkata", x: "83%", y: "39%", color: palette.teal, pods: 4, batches: 2, note: "Potential hub" },
];

export default function NetworkScreen() {
  const router = useRouter();
  const [selected, setSelected] = useState(cities[0]);
  return <ScreenContainer className="p-0"><ScrollView contentContainerStyle={local.content} showsVerticalScrollIndicator={false}>
    <View style={local.topbar}><Pressable onPress={() => router.back()} style={({ pressed }) => [local.back, pressed && ui.pressed]}><MaterialIcons name="arrow-back" size={20} color={palette.text} /></Pressable><View><Eyebrow>NATIONAL NETWORK</Eyebrow><Text style={local.title}>Scale / impact</Text></View><Pill label="Demo live" /></View>
    <Card tone="mint" style={local.hero}><View style={local.heroTop}><View style={{ flex: 1 }}><Eyebrow color={palette.ink}>RE:MATTER INDIA / 2026</Eyebrow><Text style={local.heroTitle}>The next use network is growing.</Text><Text style={local.heroText}>A simulated view of connected collection, processing, and buyer nodes.</Text></View><IconBadge name="public" color={palette.ink} background="rgba(7,26,36,0.11)" size={54} /></View></Card>
    <View style={local.kpis}><Card style={local.kpi}><Stat value="15" label="active pods" accent={palette.mint} compact /></Card><Card style={local.kpi}><Stat value="25" label="restaurants" accent={palette.teal} compact /></Card><Card style={local.kpi}><Stat value="8" label="buyer nodes" accent={palette.blue} compact /></Card></View>
    <SectionTitle title="Live city map" />
    <Card style={local.mapCard}><View style={local.legend}><View style={local.legendItem}><View style={[local.legendDot, { backgroundColor: palette.mint }]} /><Text style={local.muted}>collection points</Text></View><View style={local.legendItem}><View style={[local.legendDot, { backgroundColor: palette.blue }]} /><Text style={local.muted}>processing hubs</Text></View><View style={local.legendItem}><View style={[local.legendDot, { backgroundColor: palette.coral }]} /><Text style={local.muted}>manufacturers</Text></View></View><View style={local.map}><View style={local.mapOutline} />{cities.map((city) => <Pressable key={city.name} onPress={() => { impact(); setSelected(city); }} style={[local.mapPin, { left: city.x as `${number}%`, top: city.y as `${number}%`, backgroundColor: city.color }, selected.name === city.name && local.mapPinSelected]}><Text style={local.mapPinText}>{city.name.slice(0, 1)}</Text></Pressable>)}</View><View style={local.selectedCity}><View><Text style={local.selectedName}>{selected.name}</Text><Text style={local.muted}>{selected.note}</Text></View><View style={local.cityStats}><Text style={local.cityStat}>{selected.pods} <Text style={local.cityStatLabel}>pods</Text></Text><Text style={local.cityStat}>{selected.batches} <Text style={local.cityStatLabel}>batches</Text></Text></View></View></Card>
    <SectionTitle title="Network pulse" />
    <Card style={local.pulseCard}><View style={local.pulseRow}><IconBadge name="local-shipping" color={palette.teal} background="rgba(103,216,186,0.12)" size={40} /><View style={local.pulseCopy}><Text style={local.cardTitle}>12 pickups optimized</Text><Text style={local.muted}>31.4 km simulated route · 1h 42m</Text></View><Pill label="-18%" /></View><View style={local.divider} /><View style={local.pulseRow}><IconBadge name="factory" color={palette.amber} background="rgba(255,203,112,0.12)" size={40} /><View style={local.pulseCopy}><Text style={local.cardTitle}>8 batches moving downstream</Text><Text style={local.muted}>Traceability maintained by passport events</Text></View><Pill label="On track" color={palette.mint} /></View><View style={local.divider} /><View style={local.pulseRow}><IconBadge name="groups" color={palette.blue} background="rgba(120,184,255,0.12)" size={40} /><View style={local.pulseCopy}><Text style={local.cardTitle}>382 participating users</Text><Text style={local.muted}>Rewarded for verified recovery, not volume</Text></View><Pill label="+24%" color={palette.blue} background="rgba(120,184,255,0.12)" /></View></Card>
    <Card style={local.impact}><Eyebrow color={palette.mint}>ESTIMATED NETWORK IMPACT</Eyebrow><View style={local.impactRow}><Text style={local.impactValue}>1,284 kg</Text><Text style={local.impactLabel}>recovered material</Text></View><View style={local.impactRow}><Text style={local.impactValue}>174</Text><Text style={local.impactLabel}>successful collections</Text></View><Text style={local.disclaimer}>Figures are simulated demo data and should be replaced with verified measurements in production.</Text></Card>
  </ScrollView></ScreenContainer>;
}

const local = StyleSheet.create({ content: { padding: 20, paddingBottom: 42, gap: 16 }, topbar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 36, height: 36, borderRadius: 12, backgroundColor: palette.surface, alignItems: "center", justifyContent: "center" }, title: { color: palette.text, fontSize: 25, fontWeight: "900", marginTop: 3 }, hero: { padding: 20 }, heroTop: { flexDirection: "row", alignItems: "center", gap: 12 }, heroTitle: { color: palette.ink, fontSize: 23, lineHeight: 27, fontWeight: "900", marginTop: 7 }, heroText: { color: "rgba(7,26,36,0.7)", fontSize: 12, lineHeight: 18, marginTop: 7 }, kpis: { flexDirection: "row", gap: 8 }, kpi: { flex: 1, padding: 13, minHeight: 78 }, mapCard: { gap: 13, padding: 14 }, legend: { flexDirection: "row", flexWrap: "wrap", gap: 11 }, legendItem: { flexDirection: "row", alignItems: "center", gap: 5 }, legendDot: { width: 7, height: 7, borderRadius: 4 }, muted: { color: palette.muted, fontSize: 10 }, map: { height: 285, borderRadius: 18, backgroundColor: "#0A2028", position: "relative", overflow: "hidden", borderWidth: 1, borderColor: palette.line }, mapOutline: { position: "absolute", width: 175, height: 210, borderRadius: 45, borderWidth: 1, borderColor: "rgba(103,216,186,0.28)", transform: [{ rotate: "18deg" }], left: "24%", top: "12%" }, mapPin: { position: "absolute", width: 26, height: 26, borderRadius: 13, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "#0A2028" }, mapPinSelected: { width: 33, height: 33, borderRadius: 17, borderColor: palette.text, transform: [{ translateX: -3 }, { translateY: -3 }] }, mapPinText: { color: palette.ink, fontSize: 11, fontWeight: "900" }, selectedCity: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 2 }, selectedName: { color: palette.text, fontSize: 17, fontWeight: "900" }, cityStats: { flexDirection: "row", gap: 12 }, cityStat: { color: palette.mint, fontSize: 17, fontWeight: "900" }, cityStatLabel: { color: palette.muted, fontSize: 10, fontWeight: "700" }, pulseCard: { gap: 14 }, pulseRow: { flexDirection: "row", alignItems: "center", gap: 10 }, pulseCopy: { flex: 1, gap: 3 }, cardTitle: { color: palette.text, fontSize: 13, fontWeight: "900" }, divider: { height: 1, backgroundColor: palette.line }, impact: { padding: 20, gap: 11 }, impactRow: { flexDirection: "row", alignItems: "baseline", gap: 8 }, impactValue: { color: palette.mint, fontSize: 24, fontWeight: "900" }, impactLabel: { color: palette.text, fontSize: 12, fontWeight: "700" }, disclaimer: { color: palette.muted, fontSize: 10, lineHeight: 15, fontStyle: "italic", marginTop: 3 }
});
