import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { Card, Eyebrow, IconBadge, Pill, PrimaryButton, ProgressBar, SectionTitle, palette, styles as ui } from "@/components/rematter-ui";

export default function PodScreen() {
  const router = useRouter();
  const [pickupCreated, setPickupCreated] = useState(false);
  const fill = pickupCreated ? 87 : 82;
  return (
    <ScreenContainer className="p-0"><ScrollView contentContainerStyle={local.content} showsVerticalScrollIndicator={false}>
      <View style={local.topbar}><Pressable onPress={() => router.back()} style={({ pressed }) => [local.back, pressed && ui.pressed]}><MaterialIcons name="arrow-back" size={20} color={palette.text} /></Pressable><View><Eyebrow>CONNECTED HARDWARE</Eyebrow><Text style={local.title}>Smart Pod</Text></View><Pill label="Live" /></View>
      <Card tone="mint" style={local.hero}><View style={local.heroTop}><View><Eyebrow color={palette.ink}>RM-POD-0021</Eyebrow><Text style={local.heroTitle}>Signal stable.</Text><Text style={local.heroText}>Last sync · 2 minutes ago</Text></View><View style={local.podIcon}><MaterialIcons name="sensors" size={30} color={palette.ink} /></View></View><View style={local.bigMeter}><Text style={local.fill}>{fill}%</Text><Text style={local.fillLabel}>current fill level</Text><ProgressBar value={fill} color={palette.ink} height={9} /></View><View style={local.threshold}><MaterialIcons name="notifications-active" size={17} color={palette.ink} /><Text style={local.thresholdText}>Pickup threshold {pickupCreated ? "reached" : "at 85%"}</Text></View></Card>
      {!pickupCreated ? <Card style={local.trigger}><View style={local.triggerTop}><View><Eyebrow color={palette.amber}>SIMULATION CONTROL</Eyebrow><Text style={local.triggerTitle}>Test automatic pickup</Text></View><IconBadge name="local-shipping" color={palette.amber} background="rgba(255,203,112,0.13)" /></View><Text style={local.body}>Simulate the pod reaching its configured threshold and create a pickup request for the closest partner.</Text><PrimaryButton label="Trigger pickup" onPress={() => setPickupCreated(true)} icon="bolt" /></Card> : <Card tone="mint" style={local.pickup}><View style={local.triggerTop}><View><Eyebrow color={palette.ink}>AUTOMATIC PICKUP TRIGGERED</Eyebrow><Text style={local.triggerTitleDark}>Pickup request created</Text></View><IconBadge name="check-circle" color={palette.ink} background="rgba(7,26,36,0.12)" /></View><Text style={local.bodyDark}>The network assigned the nearest available collection partner.</Text><View style={local.pickupData}><View><Text style={local.labelDark}>PICKUP ID</Text><Text style={local.valueDark}>RM-PU-0481</Text></View><View><Text style={local.labelDark}>ETA</Text><Text style={local.valueDark}>38 min</Text></View><View><Text style={local.labelDark}>PARTNER</Text><Text style={local.valueDark}>Aarav Logistics</Text></View></View><PrimaryButton label="Open collection flow" onPress={() => router.push("/network")} icon="arrow-forward" variant="secondary" /></Card>}
      <SectionTitle title="Pod telemetry" />
      <View style={local.telemetryGrid}>{[{ icon: "scale" as const, label: "Weight", value: "18.4 kg", note: "↑ 2.1 kg today", color: palette.teal }, { icon: "device-thermostat" as const, label: "Temperature", value: "24.6 °C", note: "Within range", color: palette.mint }, { icon: "water-drop" as const, label: "Humidity", value: "58%", note: "Within range", color: palette.blue }, { icon: "battery-std" as const, label: "Battery", value: "91%", note: "Est. 11 days", color: palette.amber }].map((item) => <Card key={item.label} style={local.telemetryCard}><IconBadge name={item.icon} color={item.color} background={`${item.color}18`} size={34} /><Text style={local.telemetryLabel}>{item.label}</Text><Text style={local.telemetryValue}>{item.value}</Text><Text style={local.telemetryNote}>{item.note}</Text></Card>)}</View>
      <Card style={local.quality}><View style={local.qualityTop}><Text style={local.cardTitle}>Quality signals</Text><Pill label="Low risk" /></View><View style={local.signal}><Text style={local.body}>Segregation consistency</Text><Text style={local.bodyStrong}>96%</Text></View><ProgressBar value={96} /><View style={local.signal}><Text style={local.body}>Contamination risk</Text><Text style={[local.bodyStrong, { color: palette.mint }]}>Low · 4%</Text></View><ProgressBar value={4} color={palette.mint} /></Card>
    </ScrollView></ScreenContainer>
  );
}

const local = StyleSheet.create({ content: { padding: 20, paddingBottom: 42, gap: 16 }, topbar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 36, height: 36, borderRadius: 12, backgroundColor: palette.surface, alignItems: "center", justifyContent: "center" }, title: { color: palette.text, fontSize: 25, fontWeight: "900", marginTop: 3 }, hero: { gap: 18, padding: 20 }, heroTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, heroTitle: { color: palette.ink, fontSize: 28, fontWeight: "900", marginTop: 5 }, heroText: { color: "rgba(7,26,36,0.68)", fontSize: 12, marginTop: 4 }, podIcon: { width: 60, height: 60, borderRadius: 20, backgroundColor: "rgba(7,26,36,0.12)", alignItems: "center", justifyContent: "center" }, bigMeter: { gap: 8 }, fill: { color: palette.ink, fontSize: 58, lineHeight: 60, fontWeight: "900", letterSpacing: -2 }, fillLabel: { color: "rgba(7,26,36,0.65)", fontSize: 12, fontWeight: "800" }, threshold: { flexDirection: "row", gap: 7, alignItems: "center", padding: 11, borderRadius: 12, backgroundColor: "rgba(7,26,36,0.09)" }, thresholdText: { color: palette.ink, fontSize: 11, fontWeight: "900" }, trigger: { gap: 14 }, triggerTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, triggerTitle: { color: palette.text, fontSize: 19, fontWeight: "900", marginTop: 6 }, triggerTitleDark: { color: palette.ink, fontSize: 19, fontWeight: "900", marginTop: 6 }, body: { color: palette.muted, fontSize: 13, lineHeight: 20 }, bodyDark: { color: "rgba(7,26,36,0.72)", fontSize: 13, lineHeight: 20 }, pickup: { gap: 14, padding: 19 }, pickupData: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 13, borderTopWidth: 1, borderBottomWidth: 1, borderColor: "rgba(7,26,36,0.18)" }, labelDark: { color: "rgba(7,26,36,0.57)", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, valueDark: { color: palette.ink, fontSize: 13, fontWeight: "900", marginTop: 4 }, telemetryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, telemetryCard: { width: "48%", gap: 7, padding: 15 }, telemetryLabel: { color: palette.muted, fontSize: 11, fontWeight: "700", marginTop: 1 }, telemetryValue: { color: palette.text, fontSize: 19, fontWeight: "900" }, telemetryNote: { color: palette.teal, fontSize: 10, fontWeight: "700" }, quality: { gap: 10 }, qualityTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 2 }, cardTitle: { color: palette.text, fontSize: 15, fontWeight: "900" }, signal: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 3 }, bodyStrong: { color: palette.text, fontSize: 13, fontWeight: "900" }, backLabel: { color: palette.muted, fontSize: 11 }
});
